# basic options
title: Sameer Choubey
author: Sameer Choubey
email: sameer.choubey98@gmail.com
description: I write.
twitter_username: SameerChoubey98
github_username:  sameerchoubey

# Build settings
markdown: kramdown
theme: minima
