# basic options
title: Welcome to my blog
author: Sameer Choubey
email: sameer.choubey98@gmail.com
description: A wonderful site
twitter_username: SameerChoubey98
github_username:  sameerchoubey

# Build settings
markdown: kramdown
theme: minima
